Various improvements added
EOS-uiux-Solutions/eos-icons-landing pull request #49
Opened 2022-02-19 16:50 UTC by AnshumanDhiman

Fixed #44 Added various improvements fixing typos, dead link and various responsiveness issues.

2022-02-21 14:54 UTC, vinayaksh42 requested changes

2022-02-21 14:54 UTC, vinayaksh42 commented on src/pages/Docs.js
> +                Add the following directive to your application:
For the desktop view, the `*= require...` line should come right after the `:`
![opera_C5hD3W6YFO](https://user-images.githubusercontent.com/54861487/154976815-89012175-704e-482c-9e3d-054fea6943af.png)

2022-02-21 14:54 UTC, vinayaksh42 commented on src/pages/Docs.js
> +                <br />
For the desktop view, the `https://gitlab.com/SUSE-UIUX/eos-icons` line should come right after the `:`
![opera_3f04j5566k](https://user-images.githubusercontent.com/54861487/154977396-8e28b3c0-fe3d-425e-a09c-5382e07cc43f.png)

2022-02-21 14:54 UTC, vinayaksh42 commented on src/pages/Docs.js
> +                <div className='resp-link-edit'>
For the desktop view, the `https://github.com/EOS-uiux-Solutions/eos-icons-react` line should come right after the `:`
![opera_9NsTAZtUo2](https://user-images.githubusercontent.com/54861487/154978808-863d7dd5-5533-4a97-bdf9-03b352d83a7f.png)

2022-02-22 05:34 UTC, cyntss commented
@vinayaksh42 can you review the last changes?

2022-02-22 16:26 UTC, vinayaksh42 approved these changes
Great work @AnshumanDhiman

2022-02-22 16:26 UTC, merged