Fixed: #46: Added Border & Reduced the space between down arrow icon & option text
EOS-uiux-Solutions/eos-icons-landing pull request #50
Opened 2022-02-19 22:26 UTC by chinmaym07

https://user-images.githubusercontent.com/44670961/154821094-8c589d70-ce8f-4f41-ab1c-74a40c53687b.mp4

Signed-off-by: chinmaym07 <b418020@iiit-bh.ac.in>

2022-02-21 10:56 UTC, vinayaksh42 requested changes
The button appears to be very different from the secondary button. Checkout the `buttons.scss` file for the exact styling, or try to reuse the `Button.js` component

2022-02-22 05:39 UTC, cyntss requested changes

2022-02-22 05:39 UTC, cyntss commented on src/assets/scss/components/select.scss
> +  border: 1px solid $eos-form-element-color;
Use the same color for the border as used in the buttons. I think the $secondary variable is the right one

2022-02-22 16:01 UTC, vinayaksh42 requested changes
Great work @chinmaym07
The border now looks similar to the Secondary Button. Can you try to bring the text a little lower (Same as the `Download EOS Icons` button) and make the text similar to the Secondary Button
![opera_wBUipTyfIX](https://user-images.githubusercontent.com/54861487/155170147-3362640b-f2d0-4e73-9384-1789dadcae6f.png)
![opera_iTP0ZTblWT](https://user-images.githubusercontent.com/54861487/155170076-1a67e4d1-cb71-4d2d-b215-5129b521a36c.png)

2022-03-08 08:04 UTC, vinayaksh42 approved these changes
LGTM! @chinmaym07

2022-03-08 08:05 UTC, merged