Added UI Improvements
EOS-uiux-Solutions/eos-icons-landing pull request #51
Opened 2022-02-20 09:43 UTC by AnshumanDhiman

Fixed #48  Added various UI improvements including reduced spacing in AboutPage, Re-positioning button in the Docs Section and hiding the theme switch for Animated Icons as they are not currently available.

for hiding the theme switch I have to set the visibility criteria as when I am trying to set it by the pre-added use states, then it is creating issues.
This was the bug I encountered while using pre-added use state, I also tried creating a new state but also same problem.
![change1](https://user-images.githubusercontent.com/67755381/154836870-ff4b000e-4d3f-4508-b48f-2a64470b0fe5.jpg)

https://user-images.githubusercontent.com/67755381/154836872-33b497db-d219-4030-b3fd-ae9152c75bb9.mp4

When I used visibility, then it worked fine as shown below.
![change2](https://user-images.githubusercontent.com/67755381/154836942-f950db87-0239-45d3-855b-43f8031cde05.jpg)

https://user-images.githubusercontent.com/67755381/154836945-92b35399-e5bd-4ffc-a67c-bef80455c3b0.mp4

2022-02-21 10:42 UTC, vinayaksh42 requested changes

2022-02-21 10:42 UTC, vinayaksh42 commented on src/pages/AboutPage.jsx
> +      <div className='container-about'>
This is causing a spacing / margin issue in the mobile view. 
After your changes:
![opera_6KrSshJcv5](https://user-images.githubusercontent.com/54861487/154938410-d0ae0fdc-7c6e-45b0-a031-ad8bcd75f8ea.png)
Current Website:
![opera_fq95cLCOLx](https://user-images.githubusercontent.com/54861487/154938419-7bd0769d-e33a-4648-846c-33d1e8e0d5de.png)

2022-02-21 10:42 UTC, vinayaksh42 commented on src/pages/Docs.js
> +          <DownloadEOSicons />
The Download EOS icons button is supposed to be hidden / removed in the mobile view.
After your changes:
![opera_IISvQHNWbI](https://user-images.githubusercontent.com/54861487/154938697-973be969-1fd7-4481-ac4a-0f3123142a99.png)
Current website:
![opera_3UD6J5pyck](https://user-images.githubusercontent.com/54861487/154938754-91056319-63fa-4f6f-b343-b84b9ed7e0bb.png)

2022-02-22 05:51 UTC, cyntss commented on src/pages/AboutPage.jsx
> +      <div className='container-about'>
Using a new container class isn't a good practice as if in the future we need to adapt this class to reflect on all pages, this page would be untouched.

If we need new props on an element, it is better to leave the current container class, and add a new additional class for the different props.

This is the reason why other elements, like the titles in this case, break. because they are all tied to the original `.container` class.

2022-02-22 05:53 UTC, cyntss commented on src/assets/scss/pages/docs.scss
> +  .download-button-edit {
Let's not add new CSS. this functionality was already there. I believe the reason why it broke is also tied to the `.container ` class. Please switch it back to container and remove all the code from this commit as it isn't necessary

2022-02-22 16:19 UTC, vinayaksh42 requested changes

2022-02-22 16:19 UTC, vinayaksh42 commented on src/pages/Docs.js
> +
Can you remove the extra lines in order to keep the code a little clean.

2022-03-01 18:25 UTC, merged