Solve issue - #45 Solving issues #45 - Adding a functionality that lets the user know when they copy an icon
EOS-uiux-Solutions/eos-icons-landing pull request #71
Opened 2022-03-01 02:12 UTC by shrinishant

#45 

I've used react-toastify library to implement this feature. All the changes have been made only into HowToPanel.js file and package.json (to install the library)

2022-03-07 16:42 UTC, vinayaksh42 commented
I am unable to check your PR as `react-toastify` has not been added as a dependency.

Error message: `Module not found: Can't resolve 'react-toastify' in 'C:\Users\leega\Desktop\EOS-Mentor\eos-icons-landing\src'`

Can you add `react-toastify` to this PR?

2022-03-08 07:48 UTC, vinayaksh42 requested changes

2022-03-08 07:48 UTC, vinayaksh42 commented on src/components/HowToPanel.js
> +                    toast.info('Copied !!!', {
@shrinishant I think we should change the message to `Copied!` or `Copied to clipboard`.

2022-03-09 20:34 UTC, sarthakkundra commented
Hey @vinayaksh42. Shouldn't we create an in-house reusable toast component instead of using a library like `react-toastify`. It's ~19 KB minified which is quite huge. And seeing the usecase here I think an in-house component won't be a big task to build. Let me know what you think about that?
CC :- @shrinishant

2022-03-10 09:35 UTC, vinayaksh42 commented
> Hey @vinayaksh42. Shouldn't we create an in-house reusable toast component instead of using a library like `react-toastify`. It's ~19 KB minified which is quite huge. And seeing the usecase here I think an in-house component won't be a big task to build. Let me know what you think about that? CC :- @shrinishant

Great suggestion @sarthakkundra, I agree that an in-house toast component will be more lightweight and be a lot more customizable. @shrinishant I think we should proceed with this suggestion and try to create a toast component, let me know if you face any issue while working on it.

2022-03-10 14:10 UTC, shrinishant commented
> > Hey @vinayaksh42. Shouldn't we create an in-house reusable toast component instead of using a library like `react-toastify`. It's ~19 KB minified which is quite huge. And seeing the usecase here I think an in-house component won't be a big task to build. Let me know what you think about that? CC :- @shrinishant
> 
> Great suggestion @sarthakkundra, I agree that an in-house toast component will be more lightweight and be a lot more customizable. @shrinishant I think we should proceed with this suggestion and try to create a toast component, let me know if you face any issue while working on it.

Sure sir, that would be great but the same "react-toastify" library has been used in the user-story project recently, the link for the pr is [here](https://github.com/EOS-uiux-Solutions/user-story/pull/140). I think we should maintain consistency in both the projects. Let me know what would be the best to proceed with.

2022-03-12 04:15 UTC, vinayaksh42 commented
> It's a separate project so I think that shouldn't affect the decision here but @vinayaksh42 can take the final call.

I think it's best to maintain some level of consistency between user story and eos icons landing.

2022-03-22 19:56 UTC, cyntss commented
Very good decision @vinayaksh42 . I support consistency across projects too. It reduces maintenance overhead and knowledge is transferable.

2022-03-29 20:13 UTC, closed without merging